name: CI
on:
  push:
  pull_request:
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: 
      image: swift:5.4
    services:
      dynamodb:
        image: "amazon/dynamodb-local"
        ports:
          - 8000:8000
    steps:
    - uses: actions/checkout@master
    - name: Run tests
      run: swift test --enable-code-coverage --sanitize=thread
    - name: Setup container for codecov upload
      run: apt-get update && apt-get install curl -y
    - name: Process coverage file
      run: llvm-cov show .build/x86_64-unknown-linux-gnu/debug/VaporDynamoDBSessionsPackageTests.xctest -instr-profile=.build/debug/codecov/default.profdata > coverage.txt
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_UPLOAD_KEY }}
        file: coverage.txt

